[build]
  publish = "dist"
  command = "mkdir -p dist && cp *.html dist/ && echo 'HTML files copied to dist'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
